language: objective-c
osx_image: xcode11

before_install:
  - rvm install 2.6.4
  - rvm use 2.6.4
  - brew update
  - gem install cocoapods --pre
  - pod --version
  - pod repo remove master
  - rm -rf ~/.cocoapods
  - pod setup
  - pod install --verbose --no-repo-update

before_script:
  - export QINIU_TEST_ENV="travis"

script:
  - xcodebuild test -workspace QiniuSDK.xcworkspace -scheme QiniuSDK_iOS -configuration Release -destination 'platform=iOS Simulator,OS=11.0,name=iPhone SE' -enableCodeCoverage YES
  - xcodebuild test -workspace QiniuSDK.xcworkspace -scheme QiniuSDK_Mac -configuration Release -destination 'platform=macOS,arch=x86_64'

after_success:
  - bash <(curl -s https://codecov.io/bash)
